
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Super Wower 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: superwower
username: superwower
members: 
  - name    : hitochan777
    image   : https://avatars0.githubusercontent.com/u/6002787
    twitter : 
  - name    : watagashi
    image   : https://avatars1.githubusercontent.com/u/350677
    twitter : 
  - name    : kut-arika
    image   : https://avatars2.githubusercontent.com/u/5959324
    twitter : https://twitter.com/kut_arika
  - name    : leslie071564
    image   : https://avatars2.githubusercontent.com/u/6196765
    twitter : 
  - name    : nakao4532
    image   : https://avatars1.githubusercontent.com/u/2323607
    twitter : 
  - name    : yniu999
    image   : https://avatars0.githubusercontent.com/u/40845863
    twitter : 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude: ['package.json', 'src' , 'node_modules']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
host: "0.0.0.0"
